version: '3.9'
services:
  db:
    container_name: db
    image: postgres:16-alpine
    volumes:
      - ./.data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geolocation_service_development
    ports:
      - "5432:5432"
volumes:
  data:
